USE [master]
GO

/****** Object:  Database [recipes]    Script Date: 3/22/2014 4:29:30 PM ******/
DROP DATABASE [recipes]
GO

/****** Object:  Database [recipes]    Script Date: 3/22/2014 4:29:30 PM ******/
CREATE DATABASE [recipes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'recipes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\recipes.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'recipes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\recipes_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [recipes] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [recipes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [recipes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [recipes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [recipes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [recipes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [recipes] SET ARITHABORT OFF 
GO

ALTER DATABASE [recipes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [recipes] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [recipes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [recipes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [recipes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [recipes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [recipes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [recipes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [recipes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [recipes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [recipes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [recipes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [recipes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [recipes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [recipes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [recipes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [recipes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [recipes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [recipes] SET RECOVERY FULL 
GO

ALTER DATABASE [recipes] SET  MULTI_USER 
GO

ALTER DATABASE [recipes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [recipes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [recipes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [recipes] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [recipes] SET  READ_WRITE 
GO


